<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-FR5NQIN" failures="1" tests="1" name="Default test" time="8.62" errors="0" timestamp="20 Nov 2018 18:28:39 GMT">
  <testcase classname="Railway.LoginTest" name="TC07" time="1.024">
    <failure type="java.lang.AssertionError" message="
Expected is: Thank you for registering your account
Actual is: Create account
 expected [Thank you for registering your account] but found [Create account]">
      <![CDATA[java.lang.AssertionError: 
Expected is: Thank you for registering your account
Actual is: Create account
 expected [Thank you for registering your account] but found [Create account]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Railway.LoginTest.TC07(LoginTest.java:112)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC07 -->
  <testcase classname="Railway.LoginTest" name="TC05" time="0.0">
    <ignored/>
  </testcase> <!-- TC05 -->
  <testcase classname="Railway.LoginTest" name="TC02" time="0.0">
    <ignored/>
  </testcase> <!-- TC02 -->
  <testcase classname="Railway.LoginTest" name="TC01" time="0.0">
    <ignored/>
  </testcase> <!-- TC01 -->
  <testcase classname="Railway.LoginTest" name="TC04" time="0.0">
    <ignored/>
  </testcase> <!-- TC04 -->
  <testcase classname="Railway.LoginTest" name="TC03" time="0.0">
    <ignored/>
  </testcase> <!-- TC03 -->
  <testcase classname="Railway.LoginTest" name="TC06" time="0.0">
    <ignored/>
  </testcase> <!-- TC06 -->
</testsuite> <!-- Default test -->
