<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-11-19T13:32:54Z" name="Default suite" finished-at="2018-11-19T13:34:04Z" duration-ms="70016">
    <groups>
    </groups>
    <test started-at="2018-11-19T13:32:54Z" name="Default test" finished-at="2018-11-19T13:34:04Z" duration-ms="70016">
      <class name="Railway.LoginTest">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:32:54Z" name="beforeMethod" finished-at="2018-11-19T13:32:58Z" duration-ms="3436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TC01()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:32:58Z" name="TC01" finished-at="2018-11-19T13:33:06Z" duration-ms="7836" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:33:06Z" name="afterMethod" finished-at="2018-11-19T13:33:06Z" duration-ms="576" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:33:06Z" name="beforeMethod" finished-at="2018-11-19T13:33:09Z" duration-ms="3070" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TC02()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:33:09Z" name="TC02" finished-at="2018-11-19T13:33:19Z" duration-ms="9326" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:33:19Z" name="afterMethod" finished-at="2018-11-19T13:33:19Z" duration-ms="575" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:33:19Z" name="beforeMethod" finished-at="2018-11-19T13:33:22Z" duration-ms="3065" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TC03()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:33:22Z" name="TC03" finished-at="2018-11-19T13:33:29Z" duration-ms="7071" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User can login with wrong 'Password' expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User can login with wrong 'Password' expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Railway.LoginTest.TC03(LoginTest.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:33:29Z" name="afterMethod" finished-at="2018-11-19T13:33:30Z" duration-ms="575" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:33:30Z" name="beforeMethod" finished-at="2018-11-19T13:33:33Z" duration-ms="3064" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TC04()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:33:33Z" name="TC04" finished-at="2018-11-19T13:33:40Z" duration-ms="6493" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:33:40Z" name="afterMethod" finished-at="2018-11-19T13:33:40Z" duration-ms="579" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:33:40Z" name="beforeMethod" finished-at="2018-11-19T13:33:43Z" duration-ms="3137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="TC05()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:33:43Z" name="TC05" finished-at="2018-11-19T13:34:04Z" duration-ms="20629" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The correct message doesn't show expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The correct message doesn't show expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Railway.LoginTest.TC05(LoginTest.java:103)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Railway.LoginTest@587e5365]" started-at="2018-11-19T13:34:04Z" name="afterMethod" finished-at="2018-11-19T13:34:04Z" duration-ms="565" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- Railway.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
